### ISSUE TITLE
Errors trying to build with Rust 1.59.0

### ISSUE THREAD

**Issue by nomicode** [rhysd/fixred#1]
Hello, I am trying to build the latest release from source using the latest Rust compiler but I am getting errors:

```
/tmp/fixred-1.1.4 $ rustc --version
rustc 1.59.0 (9d1b2106e 2022-02-23)
```

```
/tmp/fixred-1.1.4 $ cargo build
   Compiling fixred v1.1.4 (/tmp/fixred-1.1.4)
warning: use of deprecated struct `clap::App`: Replaced with `Command`
 --> src/main.rs:2:12
  |
2 | use clap::{App, Arg};
  |            ^^^
  |
  = note: `#[warn(deprecated)]` on by default

warning: use of deprecated struct `clap::App`: Replaced with `Command`
  --> src/main.rs:20:19
   |
20 |     let matches = App::new("fixred")
   |                   ^^^

error[E0599]: no method named `about` found for struct `Arg` in the current scope
  --> src/main.rs:39:18
   |
39 |                 .about("Redirect only once when resolving a URL redirect")
   |                  ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
  --> src/main.rs:47:18
   |
47 |                 .about("Fix URLs which are matched to this pattern"),
   |                  ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
  --> src/main.rs:55:18
   |
55 |                 .about("Fix URLs which are NOT matched to this pattern"),
   |                  ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
  --> src/main.rs:59:18
   |
59 |                 .about(
   |                  ^^^^^ method not found in `Arg<'_>`

error[E0599]: no method named `about` found for struct `Arg` in the current scope
  --> src/main.rs:70:18
   |
70 |                 .about("Output verbose log. This is the same as setting \"info\" to $FIXRED_LOG environment variable")
   |                  ^^^^^ method not found in `Arg<'_>`

For more information about this error, try `rustc --explain E0599`.
warning: `fixred` (bin "fixred") generated 2 warnings
error: could not compile `fixred` due to 5 previous errors; 2 warnings emitted
```
